# rutas.yml
---
ruta_raíz:
    path:     /
    controller: 'funcionHomePage'
    methods:   [ GET ]

ruta_user_list:
    path:     /users
    controller: 'funcionListadoUsuarios'
    methods:
        - GET

ruta_user:
    path:     /users/{name}
    controller: 'funcionUsuario'
    defaults:
        name: _default_
    methods:
        - GET


ruta_user_form:
    path: /user/userform
    controller: 'vistaNewUser'
    methods:
      - GET

ruta_user_form_update:
    path: /users/{name}/userformupdate
    controller: 'vistaUpdateUser'
    methods:
      - GET

ruta_user_new:
    path: /user/
    controller: 'funcionNuevoUsuario'
    methods:
        - POST

ruta_user_update:
    path: /users/{name}/update
    controller: 'funcionUpdateUsuario'
    methods:
        - POST

ruta_user_find_by_email:
    path: /users/{name}
    controller: 'findUserByEmail'
    defaults:
        name: _default_
    methods:
        - GET

ruta_user_delete:
    path: /users/{name}/delete
    controller: 'funcionEliminarUsuario'
    defaults:
        name: _default_
    methods:
        - GET
        - DELETE

ruta_list_prueba:
    path:     /pruebalist
    controller: 'list_action'
    methods:
        - GET

ruta_results_list:
    path:     /results
    controller: 'funcionListadoResultados'
    methods:
        - GET

ruta_result_form:
    path: /user/resultform
    controller: 'vistaNewResult'
    methods:
        - GET

ruta_result_new:
    path: /results/
    controller: 'funcionNuevoResultado'
    methods:
        - POST

ruta_result_form_update:
    path: /results/{name}/resultformupdate
    controller: 'vistaUpdateResult'
    methods:
        - GET

ruta_result_update:
    path: /results/{name}/update
    controller: 'funcionUpdateResultado'
    methods:
        - POST

ruta_result:
    path:     /results/{name}
    controller: 'funcionResultado'
    defaults:
        name: _default_
    methods:
        - GET

ruta_user_result:
    path: /results/{name}/delete
    controller: 'funcionEliminarResultado'
    defaults:
        name: _default_
    methods:
        - GET
        - DELETE