# rutas.yml
---
ruta_raíz:
    path:     /
    controller: 'funcionHomePage'
    methods:   [ GET ]

ruta_user_list:
    path:     /users
    controller: 'funcionListadoUsuarios'
    methods:
        - GET

ruta_user:
    path:     /users/{name}
    controller: 'funcionUsuario'
    defaults:
        name: _default_
    methods:
        - GET
        - DELETE


ruta_user_form:
    path: /user/userform
    controller: 'vistaNewUser'
    methods:
      - GET

ruta_user_new:
    path: /user/
    controller: 'crearUsuario'
    methods:
        - POST

ruta_list_prueba:
    path:     /pruebalist
    controller: 'list_action'
    methods:
        - GET